/**
 * Write the nginx CSP for whatever this build actually emitted.
 *
 * ---- Why this exists -----------------------------------------------------
 *
 * The console's CSP is `script-src 'self'` with no `unsafe-inline`. That is
 * what makes it a wall rather than a header that passes a scanner: a script
 * injected into the page could not run, and could not exfiltrate anywhere the
 * policy does not already name.
 *
 * Next's static export does not cooperate with that. It emits inline scripts
 * carrying hydration data, and one more of ours that sets the theme before the
 * first paint. Three blocks, and their contents change on every build.
 *
 * The usual answer is to add `'unsafe-inline'` and stop thinking about it. On
 * the panel that can suspend every practice on the platform, that is the wrong
 * trade — it re-permits exactly the attack the policy was written to stop.
 *
 * So: hash every inline script this build produced and name them in the policy.
 * A script the build did not emit cannot run, which is the property we wanted,
 * and the cost is that the policy is generated rather than written once.
 *
 *   node scripts/csp.mjs            # writes out/csp.conf
 *   node scripts/csp.mjs --print    # to stdout
 */
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const OUT = path.join(process.cwd(), "out");
const API = process.env.API_ORIGIN ?? "https://clinq.flintdeorient.in";

/** Every .html this build produced. */
function pages(dir) {
  const found = [];
  for (const name of readdirSync(dir)) {
    const full = path.join(dir, name);
    if (statSync(full).isDirectory()) found.push(...pages(full));
    else if (name.endsWith(".html")) found.push(full);
  }
  return found;
}

const hashes = new Set();
let blocks = 0;

for (const file of pages(OUT)) {
  const html = readFileSync(file, "utf8");
  // Only scripts with no `src`. A `<script src>` is covered by 'self'.
  for (const m of html.matchAll(/<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/g)) {
    const body = m[1];
    if (!body.trim()) continue;
    blocks += 1;
    // The hash is over the exact bytes between the tags, which is what the
    // browser hashes. One stray character of whitespace and it will not match.
    hashes.add(`'sha256-${createHash("sha256").update(body, "utf8").digest("base64")}'`);
  }
}

// Not a single external origin appears in the export. `next/font` downloads
// the IBM Plex faces at build time and serves them from /_next/static/media,
// so there is no Google Fonts link to allow — which also means no third party
// gets told who opens the operator console.
//
// And no inline style survives either: the CSS is one external chunk. So this
// needs neither `unsafe-inline` on styles nor any host but its own.
const external = [...hashes].sort();

if (external.length === 0) {
  console.warn("No inline scripts found. That is suspicious — check the export.");
  process.exitCode = 1;
}

const csp = [
  "default-src 'none'",
  `script-src 'self' ${external.join(" ")}`,
  "style-src 'self'",
  "font-src 'self'",
  `connect-src ${API}`,
  "img-src 'self' data:",
  "form-action 'none'",
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "object-src 'none'",
].join("; ");

const conf = [
  "# Generated by scripts/csp.mjs — do not edit.",
  "#",
  "# The hashes name the inline scripts this build emitted. They change every",
  "# build, so this file is regenerated and re-uploaded with the export, and",
  "# nginx is reloaded. A stale copy blocks the page rather than exposing it,",
  "# which is the right way round for a mistake to fail.",
  `# ${blocks} inline block(s), ${hashes.size} distinct.`,
  "",
  `add_header Content-Security-Policy "${csp}" always;`,
  "",
].join("\n");

if (process.argv.includes("--print")) {
  process.stdout.write(conf);
} else {
  writeFileSync(path.join(OUT, "csp.conf"), conf);
  console.log(`csp.conf written — ${blocks} inline block(s), ${hashes.size} distinct hash(es)`);
}
